#!/usr/bin/env python3
"""
Fine-tune Qwen models on our generated SFT data.

This script loads SFT data generated by one_layer_sft.py and fine-tunes
a Qwen model using HuggingFace transformers and PEFT.
"""

import os
import sys
import json
import argparse
from pathlib import Path
from typing import Dict, List, Optional
from dataclasses import dataclass

import torch
from torch.utils.data import Dataset
import transformers
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq,
)
from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
    TaskType,
)
import numpy as np

# Check jinja2 version for chat template support
try:
    import jinja2
    from packaging import version
    if version.parse(jinja2.__version__) < version.parse("3.1.0"):
        print(f"WARNING: jinja2 version {jinja2.__version__} is too old for chat templates.")
        print("Chat templates require jinja2>=3.1.0. Please upgrade:")
        print("  pip install --upgrade 'jinja2>=3.1.0'")
        print("Training will fail if --no-chat-template is not used.")
except ImportError:
    pass

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# System prompts matching inference script (generate_qwen_predictions.py)
SYSTEM_PROMPTS = {
    "full": """You are an expert AI research scientist. Given inspiring research papers and a target research question, propose a novel research idea that addresses the question.

Your response should include:
- A proposed research idea with title, research question, hypothesis, proposed method, novelty claims, and experiment details

Format your response starting with "## Proposed Research".""",

    "rq_only": """You are an expert AI research scientist. Given a research question, propose a novel research idea that addresses the question.

Your response should include:
- A proposed research idea with title, hypothesis, proposed method, novelty claims, and experiment details

Format your response starting with "## Proposed Research".""",

    "papers_only": """You are an expert AI research scientist. Given a set of inspiring research papers, identify gaps and opportunities, then propose a novel research idea that builds upon their contributions.

Your response should include:
- A proposed research idea with title, research question, hypothesis, proposed method, novelty claims, and experiment details

Format your response starting with "## Proposed Research".""",

    "cot": """You are an expert AI research scientist. Given inspiring research papers and a target research question, first reason about gaps and opportunities, then propose a novel research idea.

Your response should include:
1. A reasoning section analyzing gaps, borrowing inspiration, and synthesizing ideas
2. A proposed research idea with title, research question, hypothesis, proposed method, novelty claims, and experiment details

Format the reasoning with "### Gap Analysis", "### Inspiration Borrowing", "### Synthesis" sections, then the proposal starting with "## Proposed Research".""",

    "stepwise_cot": """You are an expert AI research scientist. Given inspiring research papers and a target research question, develop a novel research idea step by step.

Your response should follow this exact structure:
1. Problem Identification reasoning (analyze gaps and inspiration)
2. Research Question + Hypothesis
3. Method Design reasoning (how to approach the problem)
4. Proposed Method + Novelty Claims
5. Experiment Design reasoning (how to validate)
6. Experiment Details

Use "### Step 1: Problem Identification", "### Step 2: Method Design Reasoning", "### Step 3: Experiment Design Reasoning" for reasoning sections, and "## Proposed Research" before the proposal sections.""",
}


@dataclass
class SFTExample:
    """SFT training example."""
    prompt: str
    completion: str
    tree_id: str
    root_paper_title: str


class SFTDataset(Dataset):
    """Dataset for SFT training."""

    def __init__(
        self,
        data: List[SFTExample],
        tokenizer: AutoTokenizer,
        max_length: int = 2048,
        prompt_template: str = None,
        use_chat_template: bool = False,
        system_prompt: str = None
    ):
        self.data = data
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.use_chat_template = use_chat_template
        self.system_prompt = system_prompt or "You are a helpful research assistant."

        # Default prompt template (used only when not using chat template)
        if prompt_template is None:
            self.prompt_template = "{prompt}\n\n## Response:\n{completion}"
        else:
            self.prompt_template = prompt_template

    def __len__(self):
        return len(self.data)

    def _format_with_chat_template(self, prompt: str, completion: str) -> tuple:
        """Format using Qwen's native chat template. Returns (full_text, prompt_text)."""
        # Build messages for full conversation
        messages = [
            {"role": "system", "content": self.system_prompt},
            {"role": "user", "content": prompt},
            {"role": "assistant", "content": completion}
        ]
        full_text = self.tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=False
        )
        
        # Build messages for prompt only (to find where completion starts)
        prompt_messages = [
            {"role": "system", "content": self.system_prompt},
            {"role": "user", "content": prompt}
        ]
        prompt_text = self.tokenizer.apply_chat_template(
            prompt_messages, tokenize=False, add_generation_prompt=True
        )
        
        return full_text, prompt_text

    def __getitem__(self, idx):
        example = self.data[idx]

        # Format the full text
        if self.use_chat_template:
            full_text, prompt_text = self._format_with_chat_template(
                example.prompt, example.completion
            )
        else:
            full_text = self.prompt_template.format(
                prompt=example.prompt,
                completion=example.completion
            )
            prompt_text = self.prompt_template.format(
                prompt=example.prompt,
                completion=""
            )
        
        # Append EOS token so model learns when to stop generating
        if self.tokenizer.eos_token and not full_text.endswith(self.tokenizer.eos_token):
            full_text = full_text + self.tokenizer.eos_token

        # Tokenize
        tokenized = self.tokenizer(
            full_text,
            truncation=True,
            padding=False,
            max_length=self.max_length,
            return_tensors=None
        )

        # Create labels (mask prompt tokens)
        input_ids = tokenized["input_ids"]
        labels = input_ids.copy()

        # Find where the completion starts and mask prompt tokens
        if self.use_chat_template:
            prompt_tokens = self.tokenizer(
                prompt_text,
                add_special_tokens=False,
                return_tensors=None
            )["input_ids"]
            for i in range(len(prompt_tokens)):
                if i < len(labels):
                    labels[i] = -100
        else:
            completion_start = full_text.find(example.completion)
            if completion_start >= 0:
                prompt_tokens = self.tokenizer(
                    prompt_text,
                    add_special_tokens=False,
                    return_tensors=None
                )["input_ids"]

                # Mask prompt tokens in labels
                for i in range(len(prompt_tokens)):
                    if i < len(labels):
                        labels[i] = -100

        return {
            "input_ids": input_ids,
            "attention_mask": tokenized["attention_mask"],
            "labels": labels,
        }


def load_sft_data(jsonl_file: str) -> List[SFTExample]:
    """Load SFT data from JSONL file."""
    examples = []

    with open(jsonl_file, 'r') as f:
        for line in f:
            if line.strip():
                data = json.loads(line)
                example = SFTExample(
                    prompt=data["prompt"],
                    completion=data["completion"],
                    tree_id=data.get("tree_id", ""),
                    root_paper_title=data.get("root_paper_title", "")
                )
                examples.append(example)

    return examples


def load_sft_data_json(json_file: str) -> List[SFTExample]:
    """Load SFT data from JSON file."""
    with open(json_file, 'r') as f:
        data = json.load(f)

    examples = []
    for item in data.get("data", data.get("examples", [])):
        example = SFTExample(
            prompt=item["prompt"],
            completion=item["completion"],
            tree_id=item.get("tree_id", ""),
            root_paper_title=item.get("root_paper_title", "")
        )
        examples.append(example)

    return examples


def create_peft_config(
    r: int = 8,
    lora_alpha: int = 16,
    lora_dropout: float = 0.05,
    target_modules: List[str] = None,
):
    """Create PEFT configuration for LoRA."""
    if target_modules is None:
        # Default target modules for Qwen models
        target_modules = [
            "q_proj", "k_proj", "v_proj", "o_proj",
            "gate_proj", "up_proj", "down_proj"
        ]

    return LoraConfig(
        r=r,
        lora_alpha=lora_alpha,
        lora_dropout=lora_dropout,
        target_modules=target_modules,
        bias="none",
        task_type=TaskType.CAUSAL_LM,
    )


def finetune_qwen(
    model_name: str,
    train_file: str,
    output_dir: str,
    num_epochs: int = 3,
    batch_size: int = 4,
    gradient_accumulation_steps: int = 4,
    learning_rate: float = 2e-5,
    max_length: int = 2048,
    lora_r: int = 8,
    lora_alpha: int = 16,
    warmup_ratio: float = 0.1,
    save_steps: int = 500,
    save_total_limit: Optional[int] = 3,
    eval_steps: Optional[int] = None,
    test_size: float = 0.1,
    seed: int = 42,
    use_fp16: bool = True,
    use_bf16: bool = False,
    load_in_8bit: bool = False,
    load_in_4bit: bool = False,
    report_to: str = "none",
    run_name: Optional[str] = None,
    resume_from_checkpoint: Optional[str] = None,
    use_chat_template: bool = False,
    system_prompt: Optional[str] = None,
    **kwargs,
):
    """
    Fine-tune a Qwen model on SFT data.

    Args:
        model_name: HuggingFace model name (e.g., "Qwen/Qwen2.5-7B-Instruct")
        train_file: Path to training data (JSON or JSONL)
        output_dir: Output directory for saved model
        num_epochs: Number of training epochs
        batch_size: Per-device batch size
        gradient_accumulation_steps: Gradient accumulation steps
        learning_rate: Learning rate
        max_length: Maximum sequence length
        lora_r: LoRA rank
        lora_alpha: LoRA alpha
        warmup_ratio: Warmup ratio
        save_steps: Save checkpoint every N steps
        eval_steps: Evaluate every N steps
        test_size: Test set size (fraction)
        seed: Random seed
        use_fp16: Use FP16 training
        use_bf16: Use BF16 training
        load_in_8bit: Load model in 8-bit
        load_in_4bit: Load model in 4-bit
    """
    print("=" * 80)
    print("QWEN SFT FINE-TUNING")
    print("=" * 80)
    print(f"Model: {model_name}")
    print(f"Train file: {train_file}")
    print(f"Output dir: {output_dir}")
    print(f"Epochs: {num_epochs}")
    print(f"Batch size: {batch_size}")
    print(f"LoRA rank: {lora_r}")
    print("=" * 80)

    # Set random seed
    torch.manual_seed(seed)
    np.random.seed(seed)

    # Load tokenizer
    print("Loading tokenizer...")
    tokenizer = AutoTokenizer.from_pretrained(
        model_name,
        trust_remote_code=True,
        padding_side="right",
    )

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # Load training data
    print("Loading training data...")
    if train_file.endswith('.jsonl'):
        train_examples = load_sft_data(train_file)
    elif train_file.endswith('.json'):
        train_examples = load_sft_data_json(train_file)
    else:
        raise ValueError(f"Unsupported file format: {train_file}")

    print(f"Loaded {len(train_examples)} training examples")
    if use_chat_template:
        print(f"Using Qwen chat template for training (system_prompt: {system_prompt or 'default'})")
    else:
        print("Using plain text prompt template (not using chat template)")

    # Split train/test if requested
    if test_size > 0:
        test_size = int(len(train_examples) * test_size)
        train_examples, test_examples = train_examples[:-test_size], train_examples[-test_size:]
        print(f"Train: {len(train_examples)}, Test: {len(test_examples)}")
    else:
        test_examples = None

    # Create datasets
    train_dataset = SFTDataset(
        train_examples, tokenizer, max_length,
        use_chat_template=use_chat_template, system_prompt=system_prompt
    )
    test_dataset = SFTDataset(
        test_examples, tokenizer, max_length,
        use_chat_template=use_chat_template, system_prompt=system_prompt
    ) if test_examples else None

    # Load model
    print("Loading model...")
    model_kwargs = {
        "trust_remote_code": True,
        "torch_dtype": torch.bfloat16 if use_bf16 else (torch.float16 if use_fp16 else torch.float32),
    }

    # Set device_map to load model directly on the correct GPU (avoids all processes piling on GPU 0)
    local_rank = int(os.environ.get("LOCAL_RANK", 0))
    model_kwargs["device_map"] = {"": local_rank}

    if load_in_8bit:
        model_kwargs["load_in_8bit"] = True
    elif load_in_4bit:
        model_kwargs["load_in_4bit"] = True
        model_kwargs["bnb_4bit_compute_dtype"] = torch.float16

    model = AutoModelForCausalLM.from_pretrained(model_name, **model_kwargs)

    if load_in_8bit or load_in_4bit:
        model = prepare_model_for_kbit_training(model)

    # Enable gradient checkpointing to save memory
    model.gradient_checkpointing_enable()

    # Apply LoRA
    print("Applying LoRA...")
    peft_config = create_peft_config(r=lora_r, lora_alpha=lora_alpha)
    model = get_peft_model(model, peft_config)
    model.print_trainable_parameters()

    # Training arguments
    training_args = TrainingArguments(
        output_dir=output_dir,
        num_train_epochs=num_epochs,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        gradient_accumulation_steps=gradient_accumulation_steps,
        learning_rate=learning_rate,
        warmup_ratio=warmup_ratio,
        save_steps=save_steps,
        save_total_limit=save_total_limit,
        eval_strategy="steps" if eval_steps else "no",
        eval_steps=eval_steps,
        logging_steps=10,
        fp16=use_fp16,
        bf16=use_bf16,
        gradient_checkpointing=True,
        gradient_checkpointing_kwargs={"use_reentrant": False},
        dataloader_pin_memory=False,
        load_best_model_at_end=test_dataset is not None,
        metric_for_best_model="eval_loss" if test_dataset else None,
        greater_is_better=False,
        report_to=report_to,
        run_name=run_name,
    )

    # Data collator
    data_collator = DataCollatorForSeq2Seq(
        tokenizer=tokenizer,
        padding=True,
        return_tensors="pt",
    )

    # Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=test_dataset,
        data_collator=data_collator,
    )

    # Train
    print("Starting training...")
    resume_checkpoint = resume_from_checkpoint
    if resume_checkpoint:
        print(f"Resuming from checkpoint: {resume_checkpoint}")
    trainer.train(resume_from_checkpoint=resume_checkpoint)

    # Save final model
    print("Saving model...")
    trainer.save_model(output_dir)
    tokenizer.save_pretrained(output_dir)

    print(f"✓ Training complete! Model saved to: {output_dir}")
    print("=" * 80)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Fine-tune Qwen models on SFT data")
    parser.add_argument(
        "--model-name",
        default="Qwen/Qwen2.5-7B-Instruct",
        help="HuggingFace model name (default: Qwen/Qwen2.5-7B-Instruct)"
    )
    parser.add_argument(
        "--train-file",
        required=True,
        help="Path to training data (JSON or JSONL)"
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Output directory for saved model"
    )
    parser.add_argument(
        "--num-epochs",
        type=int,
        default=3,
        help="Number of training epochs (default: 3)"
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=4,
        help="Per-device batch size (default: 4)"
    )
    parser.add_argument(
        "--gradient-accumulation-steps",
        type=int,
        default=4,
        help="Gradient accumulation steps (default: 4)"
    )
    parser.add_argument(
        "--learning-rate",
        type=float,
        default=2e-5,
        help="Learning rate (default: 2e-5)"
    )
    parser.add_argument(
        "--max-length",
        type=int,
        default=2048,
        help="Maximum sequence length (default: 2048)"
    )
    parser.add_argument(
        "--lora-r",
        type=int,
        default=8,
        help="LoRA rank (default: 8)"
    )
    parser.add_argument(
        "--lora-alpha",
        type=int,
        default=16,
        help="LoRA alpha (default: 16)"
    )
    parser.add_argument(
        "--warmup-ratio",
        type=float,
        default=0.1,
        help="Warmup ratio (default: 0.1)"
    )
    parser.add_argument(
        "--save-steps",
        type=int,
        default=500,
        help="Save checkpoint every N steps (default: 500)"
    )
    parser.add_argument(
        "--save-total-limit",
        type=int,
        default=3,
        help="Maximum number of checkpoints to keep (default: 3). Set to None to keep all."
    )
    parser.add_argument(
        "--eval-steps",
        type=int,
        default=None,
        help="Evaluate every N steps (default: None)"
    )
    parser.add_argument(
        "--test-size",
        type=float,
        default=0.1,
        help="Test set size as fraction (default: 0.1)"
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed (default: 42)"
    )
    parser.add_argument(
        "--use-fp16",
        action="store_true",
        help="Use FP16 training"
    )
    parser.add_argument(
        "--use-bf16",
        action="store_true",
        help="Use BF16 training"
    )
    parser.add_argument(
        "--load-in-8bit",
        action="store_true",
        help="Load model in 8-bit precision"
    )
    parser.add_argument(
        "--load-in-4bit",
        action="store_true",
        help="Load model in 4-bit precision"
    )
    parser.add_argument(
        "--report-to",
        default="none",
        choices=["none", "wandb", "tensorboard", "all"],
        help="Logging integration (default: none). Use 'wandb' for Weights & Biases"
    )
    parser.add_argument(
        "--run-name",
        default=None,
        help="Name for the training run (used in wandb/tensorboard)"
    )
    parser.add_argument(
        "--wandb-project",
        default="qwen-sft",
        help="Wandb project name (default: qwen-sft)"
    )
    parser.add_argument(
        "--resume-from-checkpoint",
        default=None,
        help="Path to a checkpoint directory to resume training from"
    )
    parser.add_argument(
        "--no-chat-template",
        action="store_true",
        help="Disable chat template (use plain text format). Not recommended for new training."
    )
    parser.add_argument(
        "--prompt-mode",
        default="stepwise_cot",
        choices=["full", "rq_only", "papers_only", "cot", "stepwise_cot"],
        help="Prompt mode determining system prompt (default: stepwise_cot). Must match inference mode."
    )
    parser.add_argument(
        "--system-prompt",
        default=None,
        help="Custom system prompt (overrides --prompt-mode if provided)"
    )

    args = parser.parse_args()
    
    # Resolve system prompt from mode or custom
    if args.system_prompt:
        system_prompt = args.system_prompt
    else:
        system_prompt = SYSTEM_PROMPTS.get(args.prompt_mode)
    
    # Set wandb project if using wandb
    if args.report_to == "wandb":
        import os
        os.environ['WANDB_API_KEY'] = os.getenv('WANDB_API_KEY')
        os.environ["WANDB_PROJECT"] = args.wandb_project

    finetune_qwen(
        model_name=args.model_name,
        train_file=args.train_file,
        output_dir=args.output_dir,
        num_epochs=args.num_epochs,
        batch_size=args.batch_size,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        learning_rate=args.learning_rate,
        max_length=args.max_length,
        lora_r=args.lora_r,
        lora_alpha=args.lora_alpha,
        warmup_ratio=args.warmup_ratio,
        save_steps=args.save_steps,
        save_total_limit=args.save_total_limit,
        eval_steps=args.eval_steps,
        test_size=args.test_size,
        seed=args.seed,
        use_fp16=args.use_fp16,
        use_bf16=args.use_bf16,
        report_to=args.report_to,
        run_name=args.run_name,
        load_in_8bit=args.load_in_8bit,
        load_in_4bit=args.load_in_4bit,
        resume_from_checkpoint=args.resume_from_checkpoint,
        use_chat_template=not args.no_chat_template,
        system_prompt=system_prompt,
    )




